remote: true

experienceLevel:
  internship: true
  entry: true
  associate: true
  mid-senior level: true
  director: false
  executive: false

jobTypes:
  full-time: true
  contract: false
  part-time: false
  temporary: true
  internship: true
  other: false
  volunteer: true

date:
  all time: true
  month: dec
  week: first
  24 hours: true

positions:
  - DevOps Engineer
  - Cloud Engineer
  - AWS CLoud Engineer
  - Azure DevOps Engineer
  - AWS DevOps Engineer

locations:
  - USA

distance: 100

companyBlacklist:
  - Noir
  - Crossover

titleBlacklist:
