remote: [true]

experienceLevel:
 internship: [true]
 entry: [true]
 associate: [true]
 mid-senior level: [true]
 director: [true]
 executive: [true]

jobTypes:
 full-time: [true/false]
 contract: [false]
 part-time: [false]
 temporary: [true]
 internship: [true]
 other: [true]
 volunteer: [true]

date:
 all time: [true]
 month: [t]
 week: [true/false]
 24 hours: [true/false]

positions:
  - position1
  - position2

locations:
  - Country1
  - Country2

distance: 100

companyBlacklist:
  - Company1
  - Company2

titleBlacklist:
  - word1
  - word2